aot/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [

    #Admin Sites
    url(r'^admin/', include(admin.site.urls), name='admin'),
   

    #Sites
    url(r'^', include('website.urls')),
    url(r'^up/', include('devup.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

devup/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from devup.views import UpList, UpDetail, UpCreate, UpUpdate

app_name = 'devup'

urlpatterns = [
    url(r'^up_list$', UpList.as_view(), name='up_list'),
    url(r'^up_create$', UpCreate.as_view(), name='up_create'),
    url(r'^up_detail/(?P<pk>[-\w]+)/$', UpDetail.as_view(), name='up_detail'),
    url(r'^(?P<pk>[-\w]+)/$', UpDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update$', UpUpdate.as_view(), name='update'),

]

usermanager/urls.py
from django.conf.urls import url
from . import views

app_name = 'usermanager'

urlpatterns = [
    #url(r'^uindex/$', views.uindex, name='uindex'),
    url(r'^register/$',views.register, name='register'),
    url(r'^login_user/$',views.login_user, name='login_user'),
    url(r'^logout_user/$',views.logout_user, name='logout_user'),
    url(r'^create_uprofile/$',views.create_uprofile, name='create_uprofile' ),
]

website/urls.py
from django.conf.urls import url
from . import views

app_name = 'website'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

devup/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User
from multiselectfield import MultiSelectField
from django.db import models
import datetime
from devup.choices import SALUTATION_LIST
# Create your models here.

#class SaluteList(models.Model):
#    id = models.AutoField(primary_key=True)
#    name = models.CharField(max_length=6, blank=True)

#    def __str__(self):
#        return self.name

class UsrProfile(models.Model):
       
    user = models.ForeignKey(User, default=1)
    salutation = models.IntegerField(max_length=2, choices=SALUTATION_LIST, default=1)  
    firstname = models.CharField(max_length=25, blank=True)
    lastname = models.CharField(max_length=25, blank=True)
    usercover = models.FileField(upload_to='profile_pictures/', blank=True)
    usermobile = models.IntegerField(max_length=8,blank=True)
    dob = models.DateField(default='1920-01-01',)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('devup:detail', kwargs={'pk': self.pkb})

usermanager/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User
from multiselectfield import MultiSelectField
from django.db import models
import datetime
# Create your models here.

class UserSalute(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=6, blank=True)

    def __str__(self):
        return self.name



class UserProfile(models.Model):
    user = models.ForeignKey(User, default=1)
    salutation = models.OneToOneField(UserSalute, blank=True)
    usercover = models.FileField(upload_to='profile_pictures/', blank=True)
    usermobile = models.DecimalField(max_digits=8, decimal_places=0, blank=True)
    dob = models.DateField(default='1920-01-01',)

    def __str__(self):
        return self.user.username

website/models.py
from django.db import models

# Create your models here.

devup/forms.py
from django import forms
from django.forms.extras import SelectDateWidget
from django.contrib.auth.models import User
from devup.models import UsrProfile
from devup.choices import SALUTATION_LIST
from functools import partial

DateInput = partial(forms.DateInput, {'class': 'datepicker'})



class UsrProfileForm(forms.ModelForm):
    salutation = forms.ChoiceField(choices = SALUTATION_LIST,required=True)
    dob = forms.DateField(widget=DateInput())


    class Meta:
        model = UsrProfile
       
        fields = [
            'salutation',
            'firstname', 
            'lastname', 
            'usercover', 
            'usermobile', 
            'dob',
            ]

usermanager/forms.py
from django import forms
from django.contrib.auth.models import User
from usermanager.models import UsrProfile




class UserForm1(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name']

class UserForm2(forms.ModelForm):

    class Meta:
        model = UsrProfile
        fields = ['salutation', 'usercover', 'usermobile',]



        

devup/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate 
from django.contrib.auth import login 
from django.contrib.auth import logout
from django.http import HttpRequest 
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.base import RedirectView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.utils import timezone
from django.core.urlresolvers import reverse_lazy
from multiselectfield import MultiSelectField

#devup imports
from devup.models import UsrProfile
from devup.forms import UsrProfileForm
from devup.choices import SALUTATION_LIST

#definitions
app_name = 'devup'


#file types
AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

# Create your views here.
# Main views below ListView, DetailView, CreateView, UpdateView

class UpList(ListView):

    model = UsrProfile
    template_name_suffix = '_list' or '_menu'

    def dispatch(self, *args, **kwargs):
        return super(UpList, self).dispatch(*args, **kwargs)

class UpDetail(DetailView):

    model = UsrProfile

    def dispatch(self, *args, **kwargs):
        return super(UpDetail, self).dispatch(*args, **kwargs)

class UpCreate(CreateView):

    model = UsrProfile
    form_class = UsrProfileForm

    def dispatch(self, *args, **kwargs):
        return super(UpCreate, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.usercover = self.request.FILES['usercover']
        file_type = self.object.usercover.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in IMAGE_FILE_TYPES:
            context = {
                'UsrProfile' : UsrProfile,
                'form' : form,
                'error_message' : 'Square Image must be PNG, JPG, or JPEG',
            }
            return redirect(self.object, '/usrprofile_form.html', context)
        self.object.save()
        return redirect(self.object)

class UpUpdate(UpdateView):

    model = UsrProfile
    form_class = UsrProfileForm
    template_name_suffix = '_update'

    def dispatch(self, *args, **kwargs):
        return super(UpUpdate, self).dispatch(*args, **kwargs)

usermanager/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.db.models import Q
from .models import Uprofile
from .forms import UprofileForm, UserForm


IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

# Create your views here.

website/views.py
from django.shortcuts import render

def index(request):
       return render(request, 'index.html')

devup/templates/devup/myprofile.html
{% extend 'usrprofile_list.html' %}

<div class="container-fluid">
  <h2>Dynamic Tabs</h2>
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">Home</a></li>
    <li><a data-toggle="tab" href="#menu1">Menu 1</a></li>
    <li><a data-toggle="tab" href="#menu2">Menu 2</a></li>
    <li><a data-toggle="tab" href="#menu3">Menu 3</a></li>
  </ul>

  <div class="tab-content">
    <div id="View" class="tab-pane fade in active">
      <h3>HOME</h3>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
    <div id="menu1" class="tab-pane fade">
      <h3>Menu 1</h3>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
    <div id="menu2" class="tab-pane fade">
      <h3>Menu 2</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
    </div>
    <div id="menu3" class="tab-pane fade">
      <h3>Menu 3</h3>
      <p>Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
    </div>
  </div>
</div>

devup/templates/devup/usrprofile_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<br />
<div class="container-fluid">
<div class="row">
    <div class="col-md-6 col-md-push-3 col-lg-6 col-lg-push-3">
        <div class="card">
            <div class=""><kbd>{{user.username}}</kbd> you are adding a new item.</div>
                    <div class="card-content">
                        {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <table>
                                {{form|crispy}}
                            </table>
                                <input class="btn btn-success col-xs-5 col-sm-5  pull-left col-md-5 col-lg-5" type="submit" value="Save"/>
                                <div onclick="history.go(-1);" class="btn btn-primary col-xs-5 pull-right col-sm-5 col-md-5 col-lg-5">Back</div>
                        </form>
                    </div>
            </div>
        </div>
</div>
</div>


{% endblock %}

devup/templates/devup/usrprofile_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}


<!--Jumbotran-->
<div class="container-fluid">
  <div class="jumbotron text-center" style="background-color: rgba(0, 0, 0, 0.05); margin-top: -20px; margin-left: -50px; margin-right: -50px; overflow: hidden;">
    <h4 class="font-pompiere-md pull-left">{% block title %}My Profile{% endblock %}</h4>  
  </div>
</div>
{% for up in object_list %}
  <!--card1 only one of the button required as per business logic users are allowed to create their profile only once-->
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <!--User profile update url format /up/2/update-->
      <a href="/up/{{ up.id }}/update" class="btn btn-info btn-block pull-right"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Update</a>

{% empty %}
      <!--User profile create-->
      <a href="/up/up_create" class="btn btn-info btn-block pull-right"><i class="fa fa-plus" aria-hidden="true"></i>Create</a>
{% endfor %}
      
    </div>
  </div>
</div>
    <!--/card1-->

{% for up in object_list %}
<div class="divider"></div>
<div class="container-fluid">
  <div class="row">
    
    <!--card2-->
    <div class="col-sm-3 col-md-3 col-lg-3">
      <div class="card">
        <div class="card-image">
          <div class="grey view overlay hm-zoom hm-white-slight z-depth-0">
            {% if up.usercover %}
              <img src="{{ up.usercover.url }}" class="img-responsive img-fluid waves-effect waves-light pull-left " style="overflow:hidden" data-toggle="tooltip" title="Cover Image">
              <div class="mask"></div>
            {% else %}
              <h5>Please upload your square profile photo</h5>
            {% endif %}  
          </div>
          </div>
          <div class="card-content font-roboto-xs">
            <span>{{ up.dob }}</span>
          </div>
        </div>
        </div>
      <!--/card2-->
      <!--card3-->
        <div class="col-md-6 col-lg-6">
          <div class="card">
          <div class="card-content font-roboto-xs">
            <span>{{ up.salutation}}. {{ up.firstname }} {{up.lastname}}</span><br>
            <span>Mobile : {{ up.usermobile }}</span>
          </div>
          </div>
        </div>
        <!--/card3-->
        
</div>
<!--/row-->
</div>
<!--/container-->
{% endfor %}

{% endblock %}


{% comment %}

<!-- original link
  <tr><td>{% if perms.todo.view_todo %}<a href="{{todo.get_absolute_url}}">{{todo}}</a>{% else %}{{todo}}{% endif %}</td>
  <td>{% if perms.todo.change_todo %}<a href="{% url 'todo_update' todo.pk %}">Update</a>{% endif %} | {% if perms.todo.delete_todo %}<a href="{% url 'todo_delete' todo.pk %}">Delete</a>{% endif %}</td></tr>

<tr>
                            <td>{{ up.user.username }}</td>
                           {% if perms.todo.view_todo %}
                            <td><a href="up_detail/{{ up.id }}"> {{ todo.title }}</a></td>
                            {% else %}
                            <td>{{ todo.title }}</td>
                            {% endif %}
                            {% if perms.todo.change_todo %}
                            <td><a class="btn btn-xs btn-warning" href="todo{{ todo.id }}/update">Change</a></td>
                            {% endif %}
                            {% if perms.todo.delete_todo %}
                            <td><a class="btn btn-xs btn-danger" href="todo{{ todo.id }}/delete">Delete</a></td>
                            {% endif %}

                          </tr>



-->

{% endcomment%}

devup/templates/devup/usrprofile_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<br />
<div class="container-fluid">
<div class="row">
    <div class="col-md-6 col-md-push-3 col-lg-6 col-lg-push-3">
        <div class="card">
            <div class=""><kbd>{{user.username}}</kbd> you are updating this item.</div>
                    <div class="card-content">
                        {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <table>
                                {{form|crispy}}
                            </table>
                                <input class="btn btn-success col-xs-5 col-sm-5  pull-left col-md-5 col-lg-5" type="submit" value="Save"/>
                                <div onclick="history.go(-1);" class="btn btn-primary col-xs-5 pull-right col-sm-5 col-md-5 col-lg-5">Back</div>
                        </form>
                    </div>
            </div>
        </div>
</div>
</div>


{% endblock %}

templates/bk_base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Bethesda Cathedral{% endblock %}</title>
 

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Material Design Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Sidebar CSS -->
    <link href="{% static 'css/sidebar.css' %}" rel="stylesheet">

    <!-- Sidebar Bullets -->
    <link href="{% static 'css/sidebullets.css' %}" rel="stylesheet">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Material Design Bootstrap -->
    
    <link href="{% static 'css/mdb.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!--Other cores-->
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <!--
    <link rel="shortcut icon" href="static\favicon.ico" type="image/x-icon">
    
       
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

    <!--Custom Style Sheet-->
    <!--
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    -->
    <!-- Custom Fonts -->
   <link href="https://fonts.googleapis.com/css?family=Cinzel+Decorative|Fredericka+the+Great|Great+Vibes|Pompiere|Roboto:100" rel="stylesheet">
    <!--
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fonts/font-awesome/css/font-awesome.css' %}" rel="stylesheet" type="text/css">
    -->

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!--Custom Parallax CSS -->
    <link href="{% static 'css/parallax.css' %}" rel="stylesheet">

    <!--Custom Animations-->
     <link href="{% static 'css/animationr.css' %}" rel="stylesheet">

    <!--Application offsets -->
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="overflow-x: hidden; overflow-y: scroll;" id="page-top">
<div id="wrapper">

    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav" >
            <!--profile picture link-->
            <br>
            <br>
            <h5 class="h5-responsive text-center text-muted">BETHESDA CATHEDRAL</h5>
            
            <div class="chip box-shadow"> <!--hinge-animation-->
                    <img src="{% static 'images/bc-icon.png' %}" alt="bc-icon" class="img-responsive">
                    username
            </div>
            <div class="divider"></div>
            <!--English Menu-->
            <!--Accordion test-->
            <div class="btn-group overflow-x: hidden; overflow-y: hidden;">
                <button class="accordion">English</button>
                <div class="panel">
                    <a href="\"><h5 class="text-muted submenu sm1">Home</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm1">title two</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm1">title three</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm2">title three one</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm2">title three two</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm3">title three three one</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm4">title three three one one</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm1">title four</h5></a>
                </div>

                <button class="accordion">Mandarin</button>
                <div class="panel">
                    <a href="#"><h5 class="text-muted submenu sm1">title one</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm1">title two</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm1">title three</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm2">title three one</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm2">title three two</h5></a>
                </div>

                <button class="accordion">Others</button>
                <div class="panel">
                    <a href="#"><h5 class="text-muted submenu sm1">title one</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm1">title two</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm1">title three</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm2">title three one</h5></a>
                    <a href="#"><h5 class="text-muted submenu sm2">title three two</h5></a>
                </div>
            </div>
            <!--/Accordion-->
            <!--Mandarin Menu-->
        </ul>
    </div>
        
        
    
    <!-- /#sidebar-wrapper -->
    
    <!-- Page Content & Static Menu -->
    <div id="page-content-wrapper">
    <div class="container-fluid">
        <nav class="navbar navbar-primary navbar-fixed-top">
            <div class=""> <!--container enter-animation-->
                <a href="#menu-toggle"><i class="btn fa fa-bars pull-right" id="menu-toggle" aria-hidden="true"></i></a>             
                <a href="/accounts/login/"><i class="btn fa fa-user pull-right" aria-hidden="true"></i></a>
            </div>       
        </nav>
        
    
    
       
       {% block content %}
       {% endblock %}
       
       <!--Footer -->
       <!-- /#page-content-wrapper -->
       
       <div class="container-fluid">
            <div class="panel-footer-inverse">
            <p class="text-center text-muted"> Copyright © Bethesda Cathedral 2017. All right reserved. </p>
            </div>
            <a href="#page-top" class="page-scroll text-muted btn btn-md sr-button btn-position-top pull-right"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>
       </div>
       </div> 
    </div>
</div>
<!--all js scripts below-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/popover.js' %}"></script>

<!-- Menu toggle script -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/accordion.js' %}"></script>


<script>
        $("#menu-toggle").click( function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
</script>

<!--Go back button script-->
<script>
    function goBack() {
    window.history.back();
    }
</script>

<!--/ menu bar button script-->
<script>
    function myFunction(x) {
    x.classList.toggle("change");
    }
</script>



<!-- not required enable only if support required -->
    <!-- jQuery 3.11 -->
    <script src="{% static 'js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="{% static 'js/scrollreveal.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>

    <!-- Theme JavaScript for scroll effect -->
    <script src="{% static 'js/creative.min.js' %}"></script>
</body>
</html>

usermanager/templates/usermanager/index.html
{% extends 'templates/base.html' %}
{% block usermanager_active %}active{% endblock %}
{% block content %}
<div class="container-fluid">
    <!-- Uprofile -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Profiles</h3>
        </div>
        {% if uprofiles %}
            {% for uprofile in uprofiles %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'usermanager:detail' uprofile.id %}">
                            <img src="{{ uprofile.upicture.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ uprofile.umobile }}</h2>
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}    
            {% endfor %}   
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'usermanager:create_uprofile' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Profile
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

</div>
{% endblock %}

website/templates/website/index.html
<h1>Welcome to the home page</h1>